baseURL = "https://resume-site-6nui.vercel.app/"
title = "Anan Resume"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disableKinds = ["taxonomy", "term"]

[languages]

  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    languageDirection = "ltr"
    contentDir = "content/en"
    weight = 1
    title = "Anan Resume"

  [languages.he]
    languageCode = "he-IL"
    languageName = "עברית"
    languageDirection = "rtl"
    contentDir = "content/he"
    weight = 2
    title = "קורות החיים של ענן"
